name: 'changes-dsl labeler'
on:
  - pull_request_target

jobs:
  changes-dsl-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch origin/main
        run: |
          git fetch origin main

      - name: Clear existing label
        run: |
          curl -s \
          -X DELETE \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ github.token }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/changes-dsl' \
          || true

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H 'Authorization: token ${{ github.token }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/changes-dsl' \
          -d '{"labels":["changes-dsl"]}' \
          || true
