name: 'changes-dsl labeler'
on:
  - pull_request_target

jobs:
  changes-dsl-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch origin/main
        run: |
          git fetch origin main

      - name: Update label
        run: |
          if [ -z "$(git diff origin/main..HEAD crates/polars-plan/dsl-schema-hashes.json)" ]; then
            curl -s \
            -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ github.token }}' \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/changes-dsl' \
            || true
          else
            curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H 'Authorization: token ${{ github.token }}' \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels' \
            -d '{"labels":["changes-dsl"]}'
          fi
